server:
  port: ${PORT:8200}
hostname: ${HOSTNAME:localhost:8200}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka

spring:
  application:
    name: chat-service
  cloud:
    stream:
      function:
        definition: createdUserConsumer
        kafka:
          binder:
            brokers: "localhost:29092"
            replicationFactor: 1
        bindings:
          createdUserConsumer-in-0:
            destination: "user-created"
            content-type: application/json
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
      file-size-threshold: 2MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${BDD_USERNAME}
    password: ${BDD_PASSWORD}
    url: jdbc:postgresql://${BDD_URL}?useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true

jwt:
  header: Authorization
  secret:  ${JWT_SECRET}
  expiration: 86400

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.assignment: DEBUG